### ISSUE TITLE
pandas 2.0 gives error with model loading

### ISSUE THREAD

**Issue by annashch-insitro** [YosefLab/PopV#25]
Hello, in the current pyprpoject.toml, the pandas version is pinned as >=1.4 (https://github.com/YosefLab/PopV/blob/main/pyproject.toml#L51) 
When running tutorial, using pandas >2 (the latest release) gave errors with torch model loading (for the scvi models from Tabula). Pandas 1.5.3 was the latest that worked for me, just a heads up in case you want to consider pinning the pandas version.

**Comment by cane11** [comment]
Thanks and yes, expected and known issue. I will fix the version so PopV stays compatible with the pre-trained models.
