### ISSUE TITLE
bug in unknown cell type label handling within _onclass algo

### ISSUE THREAD

**Issue by annashch-insitro** [YosefLab/PopV#28]
I think there is a bug in this syntax: https://github.com/YosefLab/PopV/blob/main/popv/algorithms/_onclass.py#L92

Should the code block instead be something like: 
```
        for label in adata.obs[self.labels_key]:
            if label != adata.uns["unknown_celltype_label"]:
                if label not in celltype_dict:
                    logging.warning("Following label not in celltype_dict ", label)
                    ontology_id.append("unknown")
                else:
                    ontology_id.append(celltype_dict[label])
            else:
                ontology_id.append("unknown")
```
i.e. we append 'unknown if label not in celltype_dict and add an `else` clause to append cell_dict value if the `label` key is present in the dict.

**Comment by cane11** [comment]
Sounds good. The current one is expected to fail and it's not covered in the test cases. I will push the changes latter.
