### ISSUE TITLE
Support for anndata 0.9.x

### ISSUE THREAD

**Issue by DriesSchaumont** [YosefLab/PopV#30]
Hi! 
I was wondering if there are any plans to support anndata version 0.9.0?

Thanks!
Dries

**Comment by cane11** [comment]
Thanks for your interest in PopV.
PopV itself works with newer anndata versions. The only issue is the tutorial notebook. This would require retraining the reference datasets, which is planned but without ETA for now.

**Comment by DriesSchaumont** [comment]
Hi @cane11 

Good to know that popV supports anndata 0.9.x. However, when installing popV from pypi, I get the error:

<img width="453" alt="Screenshot 2023-07-07 at 21 35 14" src="https://github.com/YosefLab/PopV/assets/5946712/d834389c-6782-4528-bd0a-640103e55b3c">

Is there an issue with the version uploaded to pypi?

**Comment by cane11** [comment]
I am able to update anndata after installing PopV (this should be the correct order - pypi will complain about it but it shouldn't break things). I might spend some time changing the concatenation function soon'ish. Anndata since 0.9 doesn't cast the type and this fails during concatenation.
