### ISSUE TITLE
Missing Kidney reference from Zenodo record (KeyError: 'Kidney')

### ISSUE THREAD

**Issue by olivermccallion** [YosefLab/PopV#45]
### Report

Hi,

Thanks for producing this package. In the listed tissue options there is a 'Kidney' reference but this is not in the Zenodo reference record https://zenodo.org/api/records/7587774. I therefore get a KeyError when the tissue type is set to 'Kidney'. Is the kidney reference available and if so could the reference be updated or could you provide a link? I tried https://zenodo.org/api/records/7580707/files/pretrained_models_Kidney_ts.tar.gz/content

Thanks
Oliver

**Comment by canergen** [comment]
Thanks for the pointer. IMO we don't have a high quality kidney dataset in Tabula sapiens (it's difficult to obtain kidney tissue from organ donations).
I would recommend using https://www.kidneycellatlas.org and retrain the classifiers.
I still need to fix the notebook in that regard.

**Comment by canergen** [comment]
Tabula sapiens v2 will also contain a kidney reference. Publication is around the corner and we will update all models once ready.
