### ISSUE TITLE
WARNING: consider updating your call to make use of `computation`

### ISSUE THREAD

**Issue by shobhitagrawal1** [YosefLab/popV#53]
### Description of feature

Hey,
Sorry this is not particulary a feature request.
I would be grateful if you could shed some light on the warning: WARNING: consider updating your call to make use of `computation`
thanking you
shobhit

**Comment by canergen** [comment]
This is a warning from bbknn and they have updated their internal API. This will be soon'ish addressed when we release the next version. I have to conduct some additional tests for this version.
